# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A fast implementation of finding the mean of each vector
#' @param x A size n vector
#' @return mean of vector x
NULL

#' A fast implementation of finding the sample standard deviation of each vector
#' @param x A size n vector
#' @return sample standard deviation of vector x
NULL

#' A fast implementation of scaling the matrix using meanVec and stdVec defined in rcpp
#' @param x A size n*p matrix
#' @return scaled matrix x
#' @export
scaleMat <- function(x) {
    .Call('_fracridge_scaleMat', PACKAGE = 'fracridge', x)
}

